services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - /app/vendor
    networks:
      - laravel-playwright

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "8989:5432"
    networks:
        - laravel-playwright

networks:
    laravel-playwright:
        driver: bridge